config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :api_users,
    controllers: { sessions: "api_users/sessions" },
    defaults: { format: :json }

  root "scores#home"
  get "recent", to: "scores#recent", as: "recent_scores"
  get "recentwrs", to: "scores#recent_wrs", as: "recent_wrs"
  get "map/:map", to: "scores#map", as: "map"
  get "player/:player_id", to: "scores#player", as: "player"
  get "player", to: redirect("players")
  get "players", to: "players#index", as: "players"
  get "mostwrs", to: "players#most_wrs", as: "most_wrs"
  get "players/autocomplete_player_name", as: "players_autocomplete"
  get "servers", to: "servers#show", as: "servers"

  apipie
  namespace :api, defaults: { format: "json" } do
    get "maps", to: "maps_api#maps"
    get "map/:map", to: "scores_api#map"
    get "player/:player_id", to: "scores_api#player"
    get "record/:record_id", to: "scores_api#record"
    post "new", to: "scores_new#new"
    root to: redirect("/apidoc"), via: :all
    match "*path", to: redirect("/apidoc"), via: :all
  end
end

app/models/score.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: scores
#
#  id            :integer          not null, primary key
#  checkpoints   :integer          is an Array
#  map           :string           not null
#  match_guid    :uuid             not null
#  mode          :integer          not null
#  speed_average :float
#  speed_end     :float
#  speed_start   :float
#  speed_top     :float
#  time          :integer          not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  api_user_id   :bigint
#  player_id     :bigint           not null
#
# Indexes
#
#  index_scores_on_map_and_mode                (map,mode)
#  index_scores_on_player_id_and_map_and_mode  (player_id,map,mode) UNIQUE
#  index_scores_on_player_id_and_mode          (player_id,mode)
#
# Foreign Keys
#
#  scores_player_id_fk  (player_id => players.id) ON DELETE => cascade
#

class Score < ApplicationRecord
  belongs_to :player
  validates :map, :mode, :time, :match_guid, presence: true
  validates :mode, inclusion: { in: 0..3 }
  validates :time, numericality: {
    only_integer: true,
    greater_than: 0,
  }
  validates :player_id, uniqueness: {
    scope: [:map, :mode],
    message: "Players may only have one record per map for each mode.",
  }

  def rank_
    Score.where(map: map, mode: mode).where(time: ...time).count + 1
  end

  def self.new_score(score)
    Player.update_player_name(score[:player_id], score[:name])

    s = player_score(score[:map], score[:mode], score[:player_id])
    return false unless s.time.nil? || score[:time] < s.time

    update_score(s, score)
    WorldRecord.check(score)
    true
  end

  def self.player_scores(params)
    mode = mode_from_params(params)
    begin
      player_id = Integer(params[:player_id])
      p = Player.find(player_id)
    rescue ArgumentError, ActiveRecord::RecordNotFound
      # player id is not an int or doesn't exist
      # return name and avg as nil, medals and records as empty arrays
      return { name: nil, id: nil, medals: [], records: [] }
    end

    query = "SELECT * FROM player_scores(:p_id, :mode)"
    scores = Score.find_by_sql([query, { p_id: p.id, mode: mode }])

    total = 0
    medals = [0, 0, 0]

    scores.each do |score|
      total += score[:rank]
      medals[score[:rank] - 1] += 1 if score[:rank].between?(1, 3)
    end

    avg = total / scores.size.to_f

    {
      name: p.name,
      id: p.id,
      average: avg.round(2),
      medals: medals,
      records: scores,
    }
  end

  def self.map_scores(params)
    mode = mode_from_params(params)
    map = params[:map].downcase
    total_scores = Score.where(map: map, mode: mode).count

    limit = params[:limit].to_i.positive? ? params[:limit].to_i : nil

    query = "SELECT * FROM map_scores(:map, :mode, :limit, 0)"
    scores = Score.find_by_sql([query, { map: map, mode: mode, limit: limit }])
    { total_records: total_scores, records: scores }
  end

  def self.map_scores_paginated(params)
    mode = mode_from_params(params)
    map = params[:map].downcase
    total_scores = Score.where(map: map, mode: mode).count

    page = params[:page].to_i.positive? ? params[:page].to_i : 1

    limit = 50
    offset = (page - 1) * 50

    query = "SELECT * FROM map_scores(:map, :mode, :limit, :offset)"
    scores = Score.find_by_sql([query, { map: map, mode: mode, limit: limit, offset: offset }])
    {
      total_records: total_scores,
      records: scores,
    }
  end

  def self.player_score(map, mode, player_id)
    Score.find_or_initialize_by(map: map, mode: mode, player_id: player_id)
  end

  def self.update_score(score, new_score)
    score.time = new_score[:time]
    score.match_guid = new_score[:match_guid]
    score.api_user_id = new_score[:api_user_id]
    score.updated_at = new_score[:date] if new_score[:date]
    score.checkpoints = new_score[:checkpoints].presence || []
    score.speed_start = new_score[:speed_start] if new_score[:speed_start]
    score.speed_end = new_score[:speed_end] if new_score[:speed_end]
    score.speed_top = new_score[:speed_top] if new_score[:speed_top]
    score.speed_average = new_score[:speed_average] if new_score[:speed_average]
    score.save!
  end

  def self.mode_from_params(params)
    return params[:mode].to_i if ["0", "1", "2", "3"].include?(params[:mode])

    physics = if params[:physics]
      params[:physics].downcase
    elsif params[:factory]
      params[:factory].downcase
    else
      "pql"
    end

    w = params.fetch(:weapons, "true")
    weapons = ActiveRecord::Type::Boolean.new.cast(w)
    return weapons ? 2 : 3 if ["vql", "classic"].include?(physics)

    weapons ? 0 : 1
  end

  private_class_method :mode_from_params, :update_score
end

app/controllers/scores_controller.rb
# frozen_string_literal: true

class ScoresController < ApplicationController
  include Pagy::Backend

  # CSRF is not needed since GET requests are idempotent
  skip_before_action :verify_authenticity_token
  caches_page :home

  def home
    @total_scores = Score.count

    @recent_wrs = WorldRecord.order(updated_at: :desc).includes(:player)
      .limit(5)
    @map_scores = WorldRecord.map_scores
  end

  def map
    return unless Score.exists?(map: params[:map].downcase)

    @map = Score.map_scores_paginated(params)
    @pagy = Pagy.new(count: @map[:total_records], page: params[:page])
  end

  def player
    @player = Score.player_scores(params)
  end

  def recent
    get_recent_records(Score)
  end

  def recent_wrs
    @wrs = true
    get_recent_records(WorldRecord)
    render("recent")
  end

  private

  def get_recent_records(model)
    mode = params.fetch(:mode, -1).to_i
    records = mode.between?(0, 3) ? model.where(mode: mode) : model

    @pagy, @recent = pagy(records.order(updated_at: :desc)
                                 .includes(:player))
  end
end

app/helpers/scores_helper.rb
# frozen_string_literal: true

module ScoresHelper
  def mode_string(mode)
    mode_strings = [
      "PQL Weapons",
      "PQL Strafe",
      "VQL Weapons",
      "VQL Strafe",
    ]
    mode_strings[mode]
  end
end

app/views/scores/home.html.slim
p #{@total_scores} total records on #{@map_scores.length} maps

table.table.table-striped.table-hover.table-xtra-condensed
    caption Recent World Records
    thead
      tr
        th Map
        th Mode
        th Player
        th.text-right Time
        th.text-right Date
    tbody
      - @recent_wrs.each do |wr|
        tr
          td
            span.no-word-break
              a href='/map/#{wr.map}?mode=#{wr.mode}' #{wr.map}
          td
            span.no-word-break = mode_string(wr.mode)
          td
            a href='/player/#{wr.player_id}?mode=#{wr.mode}' #{wr.player.name}
          td
            span.pull-right.no-word-break = time_string(wr.time)
          td
            span.pull-right = wr.updated_at
= link_to 'More', recent_wrs_path

table.table.table-striped.table-hover.table-xtra-condensed
  caption World Records
  thead
    tr
      th Map
      th PQL Weapons
      th PQL Strafe
      th VQL Weapons
      th VQL Strafe
  tbody
    - @map_scores.each do |map, wrs|
      tr
        td
          span.no-word-break
            a href='/map/#{map}' #{map}
        - wrs.each do |wr|
          - if wr
            td
              a href='/player/#{wr.player_id}?mode=#{wr.mode}' #{wr.player_name}
              span.pull-right.no-word-break = time_string(wr.time)
          - else
            td
              span.pull-right -

app/views/scores/map.html.slim
- provide(:title, params[:map])

- if @map
  .row
    .col-md-4.col-sm-6.pull-right-mode
      .panel.panel-default
        .panel-heading Mode
        .panel-body
          select#mode-select.form-control
            option value='0' PQL Weapons
            option value='1' PQL Strafe
            option value='2' VQL Weapons
            option value='3' VQL Strafe
    .col-md-4.col-sm-6
      h2 = params[:map]
      p Records: #{@map[:total_records]}
  - if @map[:total_records] != 0
    table.table.table-striped.table-hover.table-xtra-condensed
      thead
        tr
          th Rank
          th Name
          th.text-right Time
          th.text-right Date
      tbody
        - @map[:records].each do |record|
          tr
            td.col-xs-1
              span.no-word-break = record[:rank]
            td.col-xs-3
              a href='/player/#{record[:player_id]}?mode=#{record[:mode]}' #{record[:name]}
            td.col-xs-4
              span.pull-right.no-word-break = time_string(record[:time])
            td.col-xs-4.text-right = record[:date]
    == pagy_bootstrap_nav(@pagy)
- else
  h3 That map doesn't exist or doesn't have any records.

app/views/scores/player.html.slim
- provide(:title, @player[:name])

- if @player[:id]
  .row
    .col-md-4.col-sm-6.pull-right-mode
      .panel.panel-default
        .panel-heading Mode
        .panel-body
          select#mode-select.form-control
            option value='0' PQL Weapons
            option value='1' PQL Strafe
            option value='2' VQL Weapons
            option value='3' VQL Strafe
    .col-md-4.col-sm-6
      h2
        a href='http://steamcommunity.com/profiles/#{@player[:id]}' #{@player[:name]}
      p
        | #{image_tag 'gold.png', size: '16', alt: 'gold medal'} #{@player[:medals][0]}
        | #{image_tag 'silver.png', size: '16', alt: 'silver medal'} #{@player[:medals][1]}
        | #{image_tag 'bronze.png', size: '16', alt: 'bronze medal'} #{@player[:medals][2]}
      ul.list-inline
        li Average rank: #{@player[:average]}
        li Total Records: #{@player[:records].length}
  - unless @player[:records].empty?
    table#player-records.table.table-striped.table-hover.table-xtra-condensed.sortable.responsive
      thead
        tr
          th Map
          th Rank
          th.sorttable_numeric.text-right Time
          th.text-right Date
      tbody
        - @player[:records].each do |record|
          tr
            td.col-xs-3
              a href='/map/#{record[:map]}?mode=#{record[:mode]}' #{record[:map]}
            td.col-xs-1
              span.no-word-break = record[:rank]
            td.col-xs-4
              span.pull-right.no-word-break = time_string(record[:time])
            td.col-xs-4.text-right = record[:date]
- else
  h3 That player doesn't exist.

app/views/scores/recent.html.slim
- if @wrs
  - provide(:title, 'Recent World Records')
- else
  - provide(:title, 'Recent Records')

form.col-md-3.col-sm-4.col-xs-7
  label for='mode' Mode
  select#mode-select.form-control
    option value='-1' All
    option value='0' PQL Weapons
    option value='1' PQL Strafe
    option value='2' VQL Weapons
    option value='3' VQL Strafe

table.table.table-striped.table-hover.table-xtra-condensed
  - if @wrs
    caption Recent World Records
  - else
    caption Recent Records
  thead
    tr
      th Map
      th Mode
      th Player
      - unless @wrs
        th Rank
      th.text-right Time
      th.text-right Date
  tbody
    - @recent.each do |record|
      tr
        td
          a href='/map/#{record.map}?mode=#{record.mode}' #{record.map}
        td = mode_string(record.mode)
        td
          a href='/player/#{record.player_id}?mode=#{record.mode}' #{record.player.name}
        - unless @wrs
          td
            span.no-word-break = record.rank_
        td
          span.pull-right.no-word-break = time_string(record.time)
        td.text-right = record.updated_at
== pagy_bootstrap_nav(@pagy)

app/views/scores/recent_scores.html.slim
- provide(:title, 'Recent World Records')

- if @recent_scores.length != 0
  table.table.table-striped.table-hover.table-condensed
    caption Recent Records
    thead
      tr
        th Map
        th Mode
        th Player
        th Rank
        th Time
        th Date
    tbody
      - @recent_scores.each do |score|
        tr
          td = link_to score.map, map_path(score.map)
          td = mode_string(score.mode)
          td = link_to score.player.name, player_path(score.player_id)
          td = score.rank_
          td = time_string(score.time)
          td = score.updated_at
  = paginate @recent_scores