config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :api_users,
    controllers: { sessions: "api_users/sessions" },
    defaults: { format: :json }

  root "scores#home"
  get "recent", to: "scores#recent", as: "recent_scores"
  get "recentwrs", to: "scores#recent_wrs", as: "recent_wrs"
  get "map/:map", to: "scores#map", as: "map"
  get "player/:player_id", to: "scores#player", as: "player"
  get "player", to: redirect("players")
  get "players", to: "players#index", as: "players"
  get "mostwrs", to: "players#most_wrs", as: "most_wrs"
  get "players/autocomplete_player_name", as: "players_autocomplete"
  get "servers", to: "servers#show", as: "servers"

  apipie
  namespace :api, defaults: { format: "json" } do
    get "maps", to: "maps_api#maps"
    get "map/:map", to: "scores_api#map"
    get "player/:player_id", to: "scores_api#player"
    get "record/:record_id", to: "scores_api#record"
    post "new", to: "scores_new#new"
    root to: redirect("/apidoc"), via: :all
    match "*path", to: redirect("/apidoc"), via: :all
  end
end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href='/' QLRace
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.dropdown
          a.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown' href='#' role='button'
            | Records
            span.caret
          ul.dropdown-menu
            li
              a href='#{recent_scores_path}' Recent Records
            li
              a href='#{recent_wrs_path}' Recent World Records
            li
              a href='#{most_wrs_path}' Most World Records
        li
          a href='#{players_path}' Players
        li
          a href='#{servers_path}' Servers
      ul.nav.navbar-right
        = render 'layouts/search_players'

app/views/layouts/_search_players.html.slim
= form_tag(players_path, method: 'get', id: 'search-form', class: 'navbar-form navbar-right') do
  = text_field_tag :search, params[:search], placeholder: 'Find Player', class: 'form-control',
    'data-autocomplete': players_autocomplete_path
  = submit_tag 'Search', name: nil, class: 'btn btn-default'

app/views/layouts/_server_info.html.slim
.panel.panel-default
  .panel-heading
    = server[:name]
  .panel-body
    ul.list-unstyled
      li
        ' IP:
        a href='steam://connect/#{server[:address]}' #{server[:address]}
      li
        ' Map:
        a href='/map/#{server[:map]}' #{server[:map]}
      li Players: #{server[:num_players]}
      li
        - if server[:players].present?
          table.table.table-striped.table-hover.table-xtra-condensed
            thead
              tr
                th Name
                th.text-right Time
            tbody
              - server[:players].each do |player|
                tr
                  td = player[:name]
                  td
                    span.pull-right.no-word-break = time_string(player[:time])

app/views/layouts/apidoc.html.slim
- provide(:title, 'API Documentation')

doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title = full_title(yield(:title))

    = favicon_link_tag 'favicon-32x32.png', rel: 'icon', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload', async: Rails.env.production?

  body
    = render 'layouts/navbar'

    .container
      .row
        .container
          = yield
          = render 'disqus' if Apipie.configuration.use_disqus?

          footer
            .row
              .col-lg-12
                ul.list-inline
                  li
                    a href='https://discord.gg/VFYwJCs' Discord
                  li
                    a href='https://github.com/QLRace' GitHub
                  li
                    a href='/apidoc' API
                  li.pull-right
                    a href='#top' Back to top
                ul.list-unstyled
                  li
                    ' Code released under the
                    a href='https://github.com/QLRace/QLRace/blob/master/LICENSE' MIT License

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title = full_title(yield(:title))

    = favicon_link_tag 'favicon-32x32.png', rel: 'icon', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload', async: Rails.env.production?

  body
    = render 'layouts/navbar'

    .container
      = yield

      footer
        .row
          .col-lg-12
            ul.list-inline
              li
                a href='https://discord.gg/VFYwJCs' Discord
              li
                a href='https://github.com/QLRace' GitHub
              li
                a href='/apidoc' API
              li.pull-right
                a href='#top' Back to top
            ul.list-unstyled
              li
                ' Code released under the
                a href='https://github.com/QLRace/QLRace/blob/master/LICENSE' MIT License